name: Go

on:
  push:
    branches: [ "github-actions" ] #[ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        ports:
          - 13306:3306
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: partition_test
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Test
      run: go test -v ./...
      env:
        MYSQL_TEST_DSN: 'root@tcp(127.0.0.1:13306)/partition_test'
